### ISSUE TITLE
Panic on underflow

### ISSUE THREAD

**Issue by casey** [CAD97/colored-diff#3]
I think that there are scenarios where this subtraction can underflow and panic:

```
if let Some(Difference::Rem(removed)) = diffs.get(i - 1) {
```

The line is here:
https://github.com/CAD97/colored-diff/blob/42ba173859f3d011b5370d14ed2f893539aed112/src/lib.rs#L75

I'm sorry for not providing a good reproduction case, I got a crash but couldn't stop to come up with a minimal reproduction

**Comment by CAD97** [comment]
If the text starts with an Add then the subtraction will underflow, thus panicking in debug mode. It will work properly in release mode. I can't patch this for a bit (I'm super busy rn), but the simple fix is just to wrapping subtract. If you send me a PR to fix it I'll pull it and push a new version sooner than I'd get to it otherwise.

**Comment by CAD97** [comment]
Fixed by #4 and released as v0.2.2! 🎉
